[package]
name = "kimi-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "kimi-gui"
path = "src/main.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
similar.workspace = true

rfd = "0.15"
eframe = "0.32"
egui_commonmark = "0.21"

kaos = { path = "../../server/kaos" }
kimi-agent = { path = "../../server/kimi-agent" }
kosong = { path = "../../server/kosong" }
wire-client = { path = "../wire-client" }
